service: pymenet-api-dummie

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

functions:
  companyContext:
    handler: src.DummieContext.app.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      # Crear una compañía
      - http:
          path: /companies/
          method: post
          cors: true
      # Obtener una compañía específica
      - http:
          path: /companies/{company_id}
          method: get
          cors: true
