service: pymenet-api-dummie

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    GCP_SA: ${ssm:/pymenet/${self:provider.stage}/GCP_SA, env:GCP_SA, ''}
    GCP_BUCKET_NAME: ${ssm:/pymenet/${self:provider.stage}/GCP_BUCKET_NAME, env:GCP_BUCKET_NAME, ''}
    AGENT_URL: ${ssm:/pymenet/${self:provider.stage}/AGENT_URL, env:AGENT_URL, ''}
    AGENT_NAME: ${ssm:/pymenet/${self:provider.stage}/AGENT_NAME, env:AGENT_NAME, ''}

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

functions:
  workspaceContext:
    handler: src.WorkspaceManagment.app.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /workspace/upload
          method: post
          cors: true

  conversationalContext:
    handler: src.ConversationalAnalytics.app.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /conversational/ask
          method: post
          cors: true
